site_name: dsRAG
site_description: Documentation for the dsRAG library
site_url: https://d-star-ai.github.io/dsRAG/
theme:
  name: material
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - Concepts:
    - Overview: concepts/overview.md
    - Knowledge Bases: concepts/knowledge-bases.md
    - Components: concepts/components.md
    - Configuration: concepts/config.md
    - Chat: concepts/chat.md
    - Citations: concepts/citations.md
    - VLM File Parsing: concepts/vlm.md
  - API:
    - KnowledgeBase: api/knowledge_base.md
    - Chat: api/chat.md
  - Community:
    - Contributing: community/contributing.md
    - Support: community/support.md
    - Professional Services: community/professional-services.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [dsrag]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: false
            show_signature_annotations: true
            separate_signature: true
            line_length: 80
            merge_init_into_class: true
            docstring_section_style: spacy

copyright: |
  &copy; 2024 dsRAG Contributors
