version: "3"
services:
  cassandra:
    image: cassandra:5
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra
    ports:
      - 9042:9042
    healthcheck:
      test: ["CMD", "cqlsh"]
      start_interval: 10s
      interval: 5s
      timeout: 15s
      retries: 6

  tests:
    build:
      context: ../
      dockerfile: docker/test.Dockerfile
    volumes:
      - ../:/app
    image: myapp-tests
    environment:
      - CO_API_KEY=$CO_API_KEY
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
      - VOYAGE_API_KEY=$VOYAGE_API_KEY
    depends_on:
      cassandra:
        condition: service_healthy
